# Use an official Node.js runtime as a parent image
FROM node:14

# Install FFmpeg
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Bundle your app's source code inside the Docker image
COPY . .

# Expose the port that your application will run on
EXPOSE 3000

# Define the command to start your application
CMD [ "node", "app.js" ]
