FROM python:3.10

EXPOSE 8005

# Set environment variables
ENV FLASK_APP=app.py
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

# USER root
# RUN apt-get update
# RUN apt-get install -y python3-pip

ADD requirements.txt .
RUN python -m pip install -r requirements.txt

# Create a directory to store model files inside the container
RUN mkdir -p /app/templates
WORKDIR /app

# Copy model files and dependencies into the container
COPY templates/ /app/templates/

# Copy the application files
# Add all necessary scripts
ADD websocket_.py /app
ADD main.py /app

# Run the application
ENTRYPOINT ["python", "-m", "main"]